name = "gen-seq"
version = "0.1.0"
keywords = ["math"]
defaultTargets = ["GenSeq"]

[leanOptions]
pp.unicode.fun = true # pretty-prints `fun a ↦ b`
autoImplicit = false

[[require]]
name = "mathlib"
scope = "leanprover-community"
rev = "v4.20.1"

[[require]]
name = "Cli"
git = "https://github.com/leanprover/lean4-cli.git"
rev = "v4.20.0"

[[require]]
name = "«doc-gen4»"
git = "https://github.com/leanprover/doc-gen4"
rev = "v4.20.1"

[[require]]
name = "sequencelib"
git = "https://github.com/provables/sequencelib.git"
rev = "b201fca66aed7826cf80debcbb7ebfb1d007f191"

[[lean_lib]]
name = "GenSeq"

[[lean_lib]]
name = "Basic"
srcDir = "GenSeq"
root = "GenSeq.Basic"

[[lean_exe]]
supportInterpreter = true
name = "genseq"
root = "Main"
needs = ["GenSeq"]
